//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq4
{
    using System;
    using System.Collections.Generic;
    
    public partial class 產品
    {
        public string 編號 { get; set; }
        public string 品名 { get; set; }
        public Nullable<int> 單價 { get; set; }
        public Nullable<int> 數量 { get; set; }
    }
}
